### ISSUE TITLE
widget.js version 2.0.105 may be forcing some users to click twice to dismiss the overlay.

### ISSUE THREAD

**Issue by kmeddings** [CrossRef/crossmark#19]
For example:

http://www.bmj.com/content/357/bmj.j1797 
http://pubs.rsc.org/en/content/articlelanding/2017/cc/c6cc07684j

I don’t know if BMJ have implemented a non-standard method of loading the Crossref widget, but it looks like 2.0.105 binds the button events twice, which might explain the problem.

This code is from the very end of widget.js 2.0.105.

document.addEventListener("DOMContentLoaded", document.CROSSMARK.bind); 
document.CROSSMARK.bind();

**Comment by robtree** [comment]
This is also reproducible at http://crossmark.crossref.org/widget/v2.0/readme.html using Chrome 58.0.3029.110 (64-bit) on Windows 10.

**Comment by kmeddings** [comment]
Will let you know when this is deployed.

**Comment by robtree** [comment]
Really appreciate the prompt fix. I can see the update to 2.0.106 in https://crossmark-cdn.crossref.org/widget/v2.0/widget.js and all of the examples appear to be in good shape. Thanks!

**Comment by afandian** [comment]
No problem!
